config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :trainers
  resources :trainers
  resources :pokemons
  patch '/capture', to: 'pokemons#capture'
  patch '/damage', to: 'pokemons#damage'
  patch '/heal', to: 'pokemons#heal'
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
	belongs_to :trainer
        validates :name, presence: true, uniqueness: true
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pokemons
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.all
  end

  def new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.update_attributes(:trainer_id => current_trainer.id, :level => 1, :health => 100)
    if @pokemon.save
      redirect_to(trainer_path(id: current_trainer.id))
    else
      flash[:error] = @pokemon.errors.full_messages.to_sentence
      redirect_to(trainer_path(id: current_trainer.id))
    end
  end


  def capture
    @pokemon = Pokemon.find(params[:id])
    pokemon_id = @pokemon.id
    @pokemon.update_attributes(:trainer_id => current_trainer.id)
    @pokemon.save
    redirect_to(:back)
  end

  def heal
    @pokemon = Pokemon.find(params[:id])
    if @pokemon.health <= 100
      @pokemon.health += 10
    end
    @pokemon.save
    redirect_to(:back)
  end

  def damage 
    @pokemon = Pokemon.find(params[:id])
    @pokemon.health -= 10
    @pokemon.save
    redirect_to(trainer_path(current_trainer.id)) 
  end

  def destroy(pokemon)
    pokemon.destroy
  end


  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :trainer_id, :level, :health)
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_filter :authenticate_trainer!

  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
    unless @trainer == current_trainer
      redirect_to :back, :alert => "Access denied."
    end
    @pokemons = Array.new()
    all_pokemons = Pokemon.all 
    all_pokemons.each do |p|
        if p.trainer_id == @trainer.id
            @pokemons.push(p)
        end
    end
  end

end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/home/index.html.erb
<h3>Welcome to PokePortal</h3>
<p><%= link_to 'Trainers:', trainers_path %> <%= Trainer.count %> registered</p>

<% if @pokemon and current_trainer %>
  <p> A wild <%= @pokemon.name %> has appeared!</p>
  <!-- REPLACE THIS LINE BELOW -->
  <%= button_to "Throw a Pokeball!", capture_path(id: @pokemon), :class => "button medium", :method => :patch %>
<% end %>

app/views/pokemons/index.html.erb
<% @pokemons.each do |pokemon| %>
  <%= link_to pokemon.name, damage_path(id: pokemon), :method => :patch %>
  <br>
<% end %>

app/views/pokemons/new.html.erb
<h3>Create Your Pokemon!</h3>
<%= simple_form_for Pokemon.new,:url => pokemons_path do |p|%>
  <%= p.input :name, placeholder:'Pikacharmander' %>
  <%= p.button :submit,'Create' %>
<% end %>

app/views/trainers/show.html.erb
<h3>Trainer</h3>
<p>Name: <%= @trainer.name if @trainer.name %></p>
<p>Email: <%= @trainer.email if @trainer.email %></p>
<%= button_to "Create New Pokemon", new_pokemon_path(id: current_trainer.id), :class => "button medium", :method => :get%>
<div>Pokemons:</div>
<br>
<div> <% @pokemons.each do |p| %>
    <% if p.health > 0 %>
      <h3><div> <%= p.name %> </div></h3>
      <div> Health: <%= p.health %> </div>
      <%= button_to "Damage!", pokemons_path(id: p), :class => "button medium", :method => :get%>
      <%= button_to "Heal", heal_path(id: p), :class => "button medium", :method => :patch %>
    <% end %>
    <% end %>